---

# Yum
- name: Install base tools (yum)
  yum: pkg={{ item }} state=present
  with_items:
    - httpie
  when: ansible_pkg_mgr == 'yum'

# Homebrew
- name: Install base tools (Homebrew)
  homebrew: name={{ item }} state=present
  become: true
  become_user: "{{ cli_tools_homebrew_user }}"
  with_items:
    - ack
    - direnv
    - httpie
    - htop
    - jq
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'

# jarg
# FIXME: make "pip install jarg" work
#- name: install jarg (pip)
#  pip: name=jarg
#  environment:
#    PATH: "{{ host_package_manager_paths }}{{ ansible_env.PATH }}"
#  when: ansible_pkg_mgr == 'homebrew' or ansible_pkg_mgr == 'macports'

# Install ack from site
- name: Make directory /opt/bin
  file: path=/opt/bin state=directory
  when: ansible_pkg_mgr != 'homebrew'
- name: Download ack
  get_url: url=http://beyondgrep.com/ack-2.14-single-file dest=/opt/bin/ack mode=0755 sha256sum=1d203cfbc52ce8f49e3992be1cd3e4d7d5dfb7daa3739e8628aa9858ccc5b9df
  when: ansible_pkg_mgr != 'homebrew'

# Install direnv from repo
- name: Clone direnv
  git: repo=https://github.com/zimbatm/direnv.git dest=/opt/direnv
  notify:
    - install direnv
  when: ansible_pkg_mgr != 'homebrew'
