---

# Yum
- name: Install CLI tools (yum)
  yum:
    name:
      - httpie
    state: present
  when: ansible_pkg_mgr == 'yum'

# Homebrew
- name: Tap Homebrew tools
  homebrew_tap:
    name: alphahydrae/tools
    state: present
  become: true
  become_user: "{{ cli_tools_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

- name: Install CLI tools (Homebrew)
  homebrew:
    name:
      - ack
      - awscli
      - bat
      - bcrypt
      - coreutils
      - direnv
      - ensure-git-repos
      - findutils
      - ffmpeg
      - fzf
      - httpie
      - htop
      - imagemagick
      - jq
      - s3cmd
      - screen
      - tcpwait
      - tldr
      - youtube-dl
    state: present
  become: true
  become_user: "{{ cli_tools_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'

# jarg
# FIXME: make "pip install jarg" work
#- name: install jarg (pip)
#  pip: name=jarg
#  environment:
#    PATH: "{{ host_package_manager_paths }}{{ ansible_env.PATH }}"
#  when: ansible_pkg_mgr == 'homebrew' or ansible_pkg_mgr == 'macports'

# Install ack from site
- name: Make directory /opt/bin
  file: path=/opt/bin state=directory
  when: ansible_pkg_mgr != 'homebrew'
- name: Download ack
  get_url: url=http://beyondgrep.com/ack-2.14-single-file dest=/opt/bin/ack mode=0755 sha256sum=1d203cfbc52ce8f49e3992be1cd3e4d7d5dfb7daa3739e8628aa9858ccc5b9df
  when: ansible_pkg_mgr != 'homebrew'

# Install direnv from repo
- name: Clone direnv
  git: repo=https://github.com/zimbatm/direnv.git dest=/opt/direnv
  notify:
    - install direnv
  when: ansible_pkg_mgr != 'homebrew'
